<style>
    .product-label {
        position: absolute;
        top: 0;
        left: 0;
        z-index: 1;
        display: inline-block;
        padding: 5px 10px;
        font-size: 14px;
        font-weight: bold;
        color: #fff;
        background-color: #FF0000;
        -webkit-transform: rotate(-45deg);
        -ms-transform: rotate(-45deg);
        transform: rotate(-45deg);
    }
</style>

<?php
/** @var $block \Ryan\ProductLabel\Block\Product\ListProduct */
/** @var $product \Magento\Catalog\Model\Product */
$product = $block->getProduct();
$label = "test";
if ($label) {
    echo '<div class="product-label">' . $label . '</div>';
}
?>
